/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbofraPaRouteImport } from './routes/abofra-pa'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AfihyiaPaRouteImport } from './routes/afihyia-pa'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurrentAccountsRouteImport } from './routes/current-accounts'
import { Route as DigitalBankingRouteImport } from './routes/digital-banking'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SusuAccountRouteImport } from './routes/susu-account'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as BranchesIdRouteImport } from './routes/branches/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbofraPaRoute = AbofraPaRouteImport.update({
  id: '/abofra-pa',
  path: '/abofra-pa',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AfihyiaPaRoute = AfihyiaPaRouteImport.update({
  id: '/afihyia-pa',
  path: '/afihyia-pa',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAccountsRoute = CurrentAccountsRouteImport.update({
  id: '/current-accounts',
  path: '/current-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalBankingRoute = DigitalBankingRouteImport.update({
  id: '/digital-banking',
  path: '/digital-banking',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SusuAccountRoute = SusuAccountRouteImport.update({
  id: '/susu-account',
  path: '/susu-account',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIdRoute = BranchesIdRouteImport.update({
  id: '/branches/$id',
  path: '/branches/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abofra-pa': typeof AbofraPaRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/afihyia-pa': typeof AfihyiaPaRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susu-account': typeof SusuAccountRoute
  '/branches/$id': typeof BranchesIdRoute
  '/branches/': typeof BranchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abofra-pa': typeof AbofraPaRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/afihyia-pa': typeof AfihyiaPaRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susu-account': typeof SusuAccountRoute
  '/branches/$id': typeof BranchesIdRoute
  '/branches': typeof BranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abofra-pa': typeof AbofraPaRoute
  '/about': typeof AboutRoute
  '/accounts': typeof AccountsRoute
  '/admin': typeof AdminRoute
  '/afihyia-pa': typeof AfihyiaPaRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/susu-account': typeof SusuAccountRoute
  '/branches/$id': typeof BranchesIdRoute
  '/branches/': typeof BranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abofra-pa'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/afihyia-pa'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/gallery'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
    | '/susu-account'
    | '/branches/$id'
    | '/branches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abofra-pa'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/afihyia-pa'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/gallery'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
    | '/susu-account'
    | '/branches/$id'
    | '/branches'
  id:
    | '__root__'
    | '/'
    | '/abofra-pa'
    | '/about'
    | '/accounts'
    | '/admin'
    | '/afihyia-pa'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/gallery'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
    | '/susu-account'
    | '/branches/$id'
    | '/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbofraPaRoute: typeof AbofraPaRoute
  AboutRoute: typeof AboutRoute
  AccountsRoute: typeof AccountsRoute
  AdminRoute: typeof AdminRoute
  AfihyiaPaRoute: typeof AfihyiaPaRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CurrentAccountsRoute: typeof CurrentAccountsRoute
  DigitalBankingRoute: typeof DigitalBankingRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoansRoute: typeof LoansRoute
  NewsRoute: typeof NewsRoute
  ProductsRoute: typeof ProductsRoute
  SavingsRoute: typeof SavingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SusuAccountRoute: typeof SusuAccountRoute
  BranchesIdRoute: typeof BranchesIdRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abofra-pa': {
      id: '/abofra-pa'
      path: '/abofra-pa'
      fullPath: '/abofra-pa'
      preLoaderRoute: typeof AbofraPaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afihyia-pa': {
      id: '/afihyia-pa'
      path: '/afihyia-pa'
      fullPath: '/afihyia-pa'
      preLoaderRoute: typeof AfihyiaPaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-accounts': {
      id: '/current-accounts'
      path: '/current-accounts'
      fullPath: '/current-accounts'
      preLoaderRoute: typeof CurrentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-banking': {
      id: '/digital-banking'
      path: '/digital-banking'
      fullPath: '/digital-banking'
      preLoaderRoute: typeof DigitalBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/susu-account': {
      id: '/susu-account'
      path: '/susu-account'
      fullPath: '/susu-account'
      preLoaderRoute: typeof SusuAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$id': {
      id: '/branches/$id'
      path: '/branches/$id'
      fullPath: '/branches/$id'
      preLoaderRoute: typeof BranchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbofraPaRoute: AbofraPaRoute,
  AboutRoute: AboutRoute,
  AccountsRoute: AccountsRoute,
  AdminRoute: AdminRoute,
  AfihyiaPaRoute: AfihyiaPaRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CurrentAccountsRoute: CurrentAccountsRoute,
  DigitalBankingRoute: DigitalBankingRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoansRoute: LoansRoute,
  NewsRoute: NewsRoute,
  ProductsRoute: ProductsRoute,
  SavingsRoute: SavingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SusuAccountRoute: SusuAccountRoute,
  BranchesIdRoute: BranchesIdRoute,
  BranchesIndexRoute: BranchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
