/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurrentAccountsRouteImport } from './routes/current-accounts'
import { Route as DigitalBankingRouteImport } from './routes/digital-banking'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoansRouteImport } from './routes/loans'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrentAccountsRoute = CurrentAccountsRouteImport.update({
  id: '/current-accounts',
  path: '/current-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalBankingRoute = DigitalBankingRouteImport.update({
  id: '/digital-banking',
  path: '/digital-banking',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansRoute = LoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/current-accounts': typeof CurrentAccountsRoute
  '/digital-banking': typeof DigitalBankingRoute
  '/faqs': typeof FaqsRoute
  '/investments': typeof InvestmentsRoute
  '/loans': typeof LoansRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRoute
  '/savings': typeof SavingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/careers'
    | '/contact'
    | '/current-accounts'
    | '/digital-banking'
    | '/faqs'
    | '/investments'
    | '/loans'
    | '/news'
    | '/products'
    | '/savings'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BranchesRoute: typeof BranchesRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CurrentAccountsRoute: typeof CurrentAccountsRoute
  DigitalBankingRoute: typeof DigitalBankingRoute
  FaqsRoute: typeof FaqsRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoansRoute: typeof LoansRoute
  NewsRoute: typeof NewsRoute
  ProductsRoute: typeof ProductsRoute
  SavingsRoute: typeof SavingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/current-accounts': {
      id: '/current-accounts'
      path: '/current-accounts'
      fullPath: '/current-accounts'
      preLoaderRoute: typeof CurrentAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-banking': {
      id: '/digital-banking'
      path: '/digital-banking'
      fullPath: '/digital-banking'
      preLoaderRoute: typeof DigitalBankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans': {
      id: '/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof LoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BranchesRoute: BranchesRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CurrentAccountsRoute: CurrentAccountsRoute,
  DigitalBankingRoute: DigitalBankingRoute,
  FaqsRoute: FaqsRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoansRoute: LoansRoute,
  NewsRoute: NewsRoute,
  ProductsRoute: ProductsRoute,
  SavingsRoute: SavingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
